name: AzureSpringCloud
on: push
env:
  #ASC_PACKAGE_PATH: /home/runner/work/spring-petclinic-microservices/spring-petclinic-microservices/spring-petclinic-api-gateway/target
  AZURE_SUBSCRIPTION: 76ef1363-bd69-411b-9be2-6c4d8bcd6d27

jobs:
  Build_all_microservice:
    runs-on: ubuntu-latest
    name: deploy to production with artifact
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v2
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: maven build, clean
        run: |
          mvn clean package
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  jobs:       
  Deploy_all_microservice:
    steps:
      - name: Deploy api-gateway
        uses: azure/spring-cloud-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
          action: Deploy
          service-name: javaspringgithubactionscicd
          app-name: gatewayserver
          use-staging-deployment: false
          package: ${{ github.workspace }}/spring-petclinic-api-gateway/target/spring-petclinic-api-gateway-2.5.1.jar
          
      - name: Deploy admin-server
        uses: azure/spring-cloud-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
          action: Deploy
          service-name: javaspringgithubactionscicd
          app-name: admin-server
          use-staging-deployment: false
          package: ${{ github.workspace }}/spring-petclinic-api-gateway/target/spring-petclinic-admin-server-2.5.1.jar
          
      - name: Deploy customers-service
        uses: azure/spring-cloud-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
          action: Deploy
          service-name: javaspringgithubactionscicd
          app-name: customers-service
          use-staging-deployment: false
          package: ${{ github.workspace }}/spring-petclinic-api-gateway/target/spring-petclinic-customers-service-2.5.1.jar
          
      - name: Deploy vets-service
        uses: azure/spring-cloud-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
          action: Deploy
          service-name: javaspringgithubactionscicd
          app-name: vets-service
          use-staging-deployment: false
          package: ${{ github.workspace }}/spring-petclinic-api-gateway/target/spring-petclinic-vets-service-2.5.1.jar
          
      - name: Deploy visits-service
        uses: azure/spring-cloud-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
          action: Deploy
          service-name: javaspringgithubactionscicd
          app-name: visits-service
          use-staging-deployment: false
          package: ${{ github.workspace }}/spring-petclinic-api-gateway/target/spring-petclinic-visits-service-2.5.1.jar
